apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
        - name: pi
          # we need aws cli for openfold params and for alignments
          image: amazon/aws-cli
          command: ["source", "<(curl -s https://raw.githubusercontent.com/rcsb/rcsb-openfold/nautilus/src/main/k8s/download_data.sh)"]
          resources:
            limits:
              memory: 200Mi
              cpu: "1"
            requests:
              memory: 50Mi
              cpu: 50m
      restartPolicy: Never
  backoffLimit: 4